version: '3.8'

services:
  app:
    image: vitas1648/crt.symfony.homework:php-fpm

  database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

